// This file has an array with all areas to use in customer creation

export const areas = [
  'Paraty',
  'São João de Meriti',
  'Balneário',
  'Bonfim',
  'Centro',
  'Colégio Naval',
  'Enseada',
  'Praia da Chácara',
  'Praia do Jardim',
  'Marinas',
  'Morro da Gloria',
  'Morro da Gloria II',
  'Morro do Perez',
  'Morro da Fortaleza',
  'Morro do Tatu',
  'Morro do Carmo',
  'Morro da Caixa Dagua',
  'Morro do Santo Antônio',
  'Morro da Carioca',
  'Morro do Abel',
  'Sapinhatuba I',
  'Sapinhatuba II',
  'Sapinhatuba III',
  'Vila Velha',
  'Ponta do sapê',
  'Retiro',
  'Ponta da Ribeira',
  'Tanguá',
  'Praia Grande',
  'Areal',
  'Ariró',
  'Belém',
  'Banqueta',
  'Bracuhy',
  'Campo Belo',
  'Caieira',
  'Encruzo da Enseada',
  'Morro da Cruz',
  'Frade',
  'Gamboa do Bracuí',
  'Gamboa do Belém',
  'Itaorna',
  'Itanema',
  'Piraquara',
  'Pontal',
  'Ponta da Cruz',
  'Ponta do Partido',
  'Japuíba',
  'Nova Angra',
  'Praia do Recife',
  'Santa Rita',
  'Serra Dágua',
  'Vila Nova',
  'Zungu',
  'Camorim Grande',
  'Camorim Pequeno',
  'Caputera I',
  'Caputera II',
  'Cantagalo',
  'Portogalo',
  'Praia do Machado',
  'Paraíso',
  'Biscaia',
  'Bnh',
  'Jacuecanga',
  'Mombaça',
  'Morro da Lambicada',
  'Morro do Moreno',
  'Água santa',
  'Ponta Leste',
  'Vila dos Pescadores',
  'Vila Petrobrás',
  'Village',
  'Verolme',
  'Monsuaba',
  'Maciéis',
  'Caetés',
  'Garatucaia',
  'Perequê',
  'Praia vermelha',
  'Morro da boa vista',
  'Praia Brava',
  'Vila Histórica',
  'Vila do abraão',
  'Praia De Araçatiba',
  'Praia Vermelha da Ilha Grande',
  'Dois Rios',
  'Bananal',
  'Saco do céu',
  'Provetá',
  'Goxuma',
  'Matariz',
];
